name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-10.14, ubuntu-16.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '8.12'
    - name: Install xvfb
      if: matrix.os == 'ubuntu-16.04'
      run: |
        export DISPLAY=:99.0
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 &
        sleep 3
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run vscode:prepublish
    - name: Check
      run: |
        npm run lint
        npm test --silent
